/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreatorsNoVirtualRouteImport } from './routes/creators-no-virtual'
import { Route as CreatorsNoDelayRouteImport } from './routes/creators-no-delay'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const CreatorsNoVirtualRoute = CreatorsNoVirtualRouteImport.update({
  id: '/creators-no-virtual',
  path: '/creators-no-virtual',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsNoDelayRoute = CreatorsNoDelayRouteImport.update({
  id: '/creators-no-delay',
  path: '/creators-no-delay',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/creators': typeof CreatorsRoute
  '/creators-no-delay': typeof CreatorsNoDelayRoute
  '/creators-no-virtual': typeof CreatorsNoVirtualRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/creators': typeof CreatorsRoute
  '/creators-no-delay': typeof CreatorsNoDelayRoute
  '/creators-no-virtual': typeof CreatorsNoVirtualRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/creators': typeof CreatorsRoute
  '/creators-no-delay': typeof CreatorsNoDelayRoute
  '/creators-no-virtual': typeof CreatorsNoVirtualRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/creators'
    | '/creators-no-delay'
    | '/creators-no-virtual'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/creators'
    | '/creators-no-delay'
    | '/creators-no-virtual'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/creators'
    | '/creators-no-delay'
    | '/creators-no-virtual'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CreatorsRoute: typeof CreatorsRoute
  CreatorsNoDelayRoute: typeof CreatorsNoDelayRoute
  CreatorsNoVirtualRoute: typeof CreatorsNoVirtualRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/creators-no-virtual': {
      id: '/creators-no-virtual'
      path: '/creators-no-virtual'
      fullPath: '/creators-no-virtual'
      preLoaderRoute: typeof CreatorsNoVirtualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators-no-delay': {
      id: '/creators-no-delay'
      path: '/creators-no-delay'
      fullPath: '/creators-no-delay'
      preLoaderRoute: typeof CreatorsNoDelayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CreatorsRoute: CreatorsRoute,
  CreatorsNoDelayRoute: CreatorsNoDelayRoute,
  CreatorsNoVirtualRoute: CreatorsNoVirtualRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
